graceful:
  shutdown.enabled: false

event:
  sqs:
    endpoint.url: http://localhost:4576
    queue.name: probation_offender_search_event_queue
    dlq.name: probation_offender_search_event_dead_letter_queue_dl
index:
  sqs:
    endpoint.url: http://localhost:4576
    queue.name: probation_offender_index_queue
    dlq.name: probation_offender_index_queue_dl
